version: "3.7"

networks:
  devpi:
    external: false

services:

  devpi_server:
    image: aegeanstudio/devpi:latest
    environment:
      - DEVPI_INIT_KEYFS_CACHE_SIZE=10000
    command:
      - /bin/sh
      - -c
      - |
        devpi-server --host=0.0.0.0 --request-timeout=30 --threads=64
    restart: always
    networks:
      - devpi
    volumes:
      - /tmp/devpi/root/.devpi:/root/.devpi:Z
    ports:
      - 3141:3141
